import BlogCart from "./blogCart";
import Header from "./header";
import Head from 'next/head'

const ListCourse = [
    {title: "AWS solution architecture associate", img: "https://s.udemycdn.com/meta/default-meta-image-v2.png", vote: 5},
    {title: "AWS solution architecture associate", img: "https://s.udemycdn.com/meta/default-meta-image-v2.png", vote: 3},
    {title: "AWS solution architecture associate", img: "https://s.udemycdn.com/meta/default-meta-image-v2.png", vote: 2},
    {title: "AWS solution architecture associate", img: "https://s.udemycdn.com/meta/default-meta-image-v2.png", vote: 4},
    {title: "AWS solution architecture associate", img: "https://s.udemycdn.com/meta/default-meta-image-v2.png", vote: 5},
]

const Home = () => {
    const ListItems = ListCourse.map((course) =>
        <BlogCart title={course.title}
                  image={course.img}
                  vote={course.vote}/>
    );

    return (
        <>
            <Head>
                <title>Exam Practice CEV7</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/cev7.png" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
            </Head>
            <div className="min-h-full">
                <Header/>
                <main>
                    <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
                        <div className="flex flex-row flex-wrap flex-shrink-0 items-center px-4 py-6 sm:px-0">
                            {ListItems}
                        </div>
                    </div>

                </main>
            </div>
        </>
    )
}
export default Home;