import BlogCart from "./blogCart";
import Header from "./header";
import Head from 'next/head'

function classNames(...classes) {
    return classes.filter(Boolean).join(' ')
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Exam Practice CEV7</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/cev7.png" />
            </Head>
            <div className="min-h-full">
                <Header/>
                <main>
                    <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
                        <div className="flex flex-row flex-wrap flex-shrink-0 items-center justify-between px-4 py-6 sm:px-0">
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                            <BlogCart/>
                        </div>
                    </div>
                </main>
            </div>
        </>
    )
}